[tox]
no_package = True
env_list = lint,smoke

[testenv:lint]
description = Check code against coding style standards
deps =
    yamllint
commands =
    yamllint --no-warnings ./snap/

[testenv:smoke]
description = Smoke test for snap
deps =
    pytest
    pyyaml
commands =
    pytest -vv --no-header --tb native --log-cli-level=INFO tests/test_smoke.py -s
