[tox]
no_package = True
env_list = lint

[testenv:lint]
description = Check code against coding style standards
deps =
    yamllint
commands =
    yamllint --no-warnings ./snap/ ./spread/tests/ ./spread.yaml

