# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Snap Store

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 8.4-26.04-test-edge
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@sd-env-production-fetch-edge
